/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ktown4u.utils;

import com.fasterxml.jackson.annotation.JsonAutoDetect;
import tools.jackson.databind.MapperFeature;
import tools.jackson.databind.json.JsonMapper;
import tools.jackson.databind.SerializationFeature;

import java.util.Arrays;
import java.util.List;
import java.util.function.Predicate;

public class PrettyJsonPrinter {
    private static final JsonMapper mapper;

    static {
        mapper = JsonMapper.builder()
                .disable(SerializationFeature.FAIL_ON_EMPTY_BEANS)
                // Jackson 3에서 기본값이 true로 변경됨. Jackson 2와 동일한 필드 순서 유지를 위해 비활성화
                .disable(MapperFeature.SORT_PROPERTIES_ALPHABETICALLY)
                .changeDefaultVisibility(vc -> vc
                        .withGetterVisibility(JsonAutoDetect.Visibility.NONE)
                        .withSetterVisibility(JsonAutoDetect.Visibility.NONE)
                        .withCreatorVisibility(JsonAutoDetect.Visibility.NONE)
                        .withIsGetterVisibility(JsonAutoDetect.Visibility.NONE)
                        .withFieldVisibility(JsonAutoDetect.Visibility.ANY))
                .build();
    }

    public static List<String> prettyPrint(Object object) {
        return Arrays.asList(
                mapper.writerWithDefaultPrettyPrinter().writeValueAsString(object)
                        .split("\n"));
    }

    public static Predicate<String> outLinesIncluding(String fieldNameToExclude) {
        return line -> !line.contains(fieldNameToExclude);
    }
}
